---
title: "BDBVimp"
output: html_notebook
---



```{r}
BDBVimp<-df5[, c('BDBV','TAFV', 'EBOV',
'SUDV','BOMBV','Village','Pig','MENV','LLOV','Cat','Duck', 'RESTm')]
```

```{r}
summary(BDBVimp)
```

```{r}
set.seed(123)
library(randomForest)
library(caret)
```

```{r}
#Create train/test split 70/30
set.seed(1234)
train <- sample(nrow(BDBVimp), 0.7*nrow(BDBVimp), replace = FALSE)
TrainSet <- BDBVimp[train,]
ValidSet <- BDBVimp[-train,]
summary(TrainSet)
```

```{r}
library(DMwR)

## Smote : Synthetic Minority Oversampling Technique To Handle Class Imbalance In Binary Classification; code below puts it at 1:1 balance
balanced.data <- SMOTE(BDBV ~., TrainSet, perc.over = 100)

as.data.frame(table(balanced.data$BDBV))
```


```{r}
rf2 <- randomForest(BDBV ~ ., data = balanced.data, importance = TRUE)
rf2
```

```{r}
#Loop to identify right mtry
a=c()
i=5
for (i in 3:8) {
  rf2 <- randomForest(BDBV ~ ., data = TrainSet, ntree = 1000, mtry = i, importance = TRUE)
  predValid <- predict(rf2, ValidSet, type = "class")
  a[i-2] = mean(predValid == ValidSet$BDBV)
}
plot(3:8,a)
```

```{r}
rf2 <- randomForest(BDBV ~ ., data = TrainSet, ntree = 1000, mtry = 7, importance = TRUE)
rf2
```

```{r}
#Red/class, black/OOB, green/predictors
library(randomForest)
plot(rf2)
```

```{r}
predicted.response <- predict(rf2, ValidSet)


confusionMatrix(data=predicted.response,  
                reference=ValidSet$BDBV)
```

```{r}
library(pROC)
rf.probs=predict(rf2,
                 newdata=ValidSet,
                 type="prob")
head(rf.probs)
```

```{r}
#Calculate ROC curve
rocCurve.rf <- roc(ValidSet$BDBV,rf.probs[,"Positive"])
#plot the ROC curve
plot(rocCurve.rf,col=c(1))
```

```{r}
auc(rocCurve.rf)
```

```{r}
library(randomForest)
create_rfplot <- function(rf, type){
  
  imp <- importance(rf, type = type, scale = F)
  
  featureImportance <- data.frame(Feature = row.names(imp), Importance = imp[,1])
  
  p <- ggplot(featureImportance, aes(x = reorder(Feature, Importance), y = Importance)) +
       geom_bar(stat = "identity", fill = "#53cfff", width = 0.65) +
       coord_flip() + 
       theme_light(base_size = 20) +
       theme(axis.title.x = element_text(size = 15, color = "black"),
             axis.title.y = element_blank(),
             axis.text.x  = element_text(size = 15, color = "black"),
             axis.text.y  = element_text(size = 15, color = "black")) 
  return(p)
}
```

```{r}
create_rfplot(rf2, type = 1)
```
```{r}
saveRDS(rf2, file="C:/Users/rothg/Desktop/Dissertation Proposal/Random Forests and Feature Importances/BDBV/BDBVRFmodel.rda")
```

```{r}

```

